<?php
if (isset($_SERVER['HTTP_ORIGIN'])) {
  //header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
  header("Access-Control-Allow-Origin: *");
  header('Access-Control-Allow-Credentials: true');    
  header("Access-Control-Allow-Methods: GET, POST, OPTIONS"); 
}   
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
      header("Access-Control-Allow-Methods: GET, POST, OPTIONS");         
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
      header("Access-Control-Allow-Headers:{$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

  exit(0);
}

$value = $_POST;
//echo "<pre>";print_r($value);die;

$xmllinesTax = '';

foreach($value['invoice_tax'] as $linesTax)
{
     $xmllinesTax.=
        "<LEDGERENTRIES.LIST>
        <ADDLALLOCTYPE/>
        <ROUNDTYPE/>
        <LEDGERNAME>".$linesTax['tax_code']."</LEDGERNAME>
        <VOUCHERFBTCATEGORY/>
        <GSTCLASS/>
        <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
        <LEDGERFROMITEM>No</LEDGERFROMITEM>
        <ISPARTYLEDGER>No</ISPARTYLEDGER>
        <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
        <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
        <AMOUNT>-".number_format($linesTax['tax_value'],2,'.',',')."</AMOUNT>
        <VATEXPAMOUNT>-".number_format($linesTax['tax_value'],2,'.',',')."</VATEXPAMOUNT>
        <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
        <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
        <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
        <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
        <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
        <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
        <INVENTORYALLOCATIONS.LIST>       </INVENTORYALLOCATIONS.LIST>
        <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
        <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
        <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
        <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
        <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
        <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
        <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
        <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
        <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
        <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
        <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
        <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
        <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
        <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
        </LEDGERENTRIES.LIST>";
}

$xmllines = '';

foreach($value['invoice_lines'] as $lines) {

  //print_r(floatval($lines['line_quantity']));die;

  $quentity = floatval($lines['line_quantity']);

  $xmllines.= 
         "<ALLINVENTORYENTRIES.LIST>
          <STOCKITEMNAME>Painting</STOCKITEMNAME>
          <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
          <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
          <ISAUTONEGATE>No</ISAUTONEGATE>
          <ISSCRAP>No</ISSCRAP>
          <RATE>".number_format($lines['unit_price'],2,'.',',')."</RATE>
          <DISCOUNT>".$lines['discount_percentage']."</DISCOUNT>
          <AMOUNT>-".number_format($lines['line_base_amount'],2,'.',',')."</AMOUNT>
          <ACTUALQTY>".$lines['line_quantity']."</ACTUALQTY>
          <BILLEDQTY>".$lines['line_quantity']."</BILLEDQTY>
          <ISINCLTAXRATEFIELDEDITED>No</ISINCLTAXRATEFIELDEDITED>
          <TEMPRATE> 7</TEMPRATE>
          <BATCHALLOCATIONS.LIST>       </BATCHALLOCATIONS.LIST>
          <ACCOUNTINGALLOCATIONS.LIST>
           <LEDGERNAME>Purchase A/C for Metrics</LEDGERNAME>
           <GSTCLASS/>
           <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
           <LEDGERFROMITEM>No</LEDGERFROMITEM>
           <ISPARTYLEDGER>No</ISPARTYLEDGER>
           <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
           <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
           <AMOUNT>-".number_format($lines['line_base_amount'],2,'.',',')."</AMOUNT>
           <SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
           <BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
           <BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
           <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
           <OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
           <ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
           <AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
           <INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
           <DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
           <EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
           <RATEDETAILS.LIST>        </RATEDETAILS.LIST>
           <SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
           <STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
           <EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
           <TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
           <TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
           <TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
           <VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
           <REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
           <INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
           <VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
           <ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
          </ACCOUNTINGALLOCATIONS.LIST>
          <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
          <SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
          <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
          <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
          <EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
          <EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
         </ALLINVENTORYENTRIES.LIST>";

          //echo"<pre>";print_r($xmllines);die;
}

      $xml = '';
      $xml.= "<ENVELOPE>
      <HEADER>
      <TALLYREQUEST>Import Data</TALLYREQUEST>
      </HEADER>
      <BODY>
      <IMPORTDATA>
        <REQUESTDESC>
        <REPORTNAME>Vouchers</REPORTNAME>
        <STATICVARIABLES>
          <SVCURRENTCOMPANY>Metrics</SVCURRENTCOMPANY>
        </STATICVARIABLES>
        </REQUESTDESC>
        <REQUESTDATA>
        <TALLYMESSAGE xmlns:UDF='TallyUDF'>
          <VOUCHER REMOTEID='' VCHTYPE='Purchase' ACTION='Create' OBJVIEW='Invoice Voucher View'>
          <ADDRESS.LIST TYPE='String'>
            <ADDRESS>".$value['vendor_state']."</ADDRESS>
          </ADDRESS.LIST>
          <DATE>20220829</DATE>
          <REFERENCEDATE>20220829</REFERENCEDATE>
          <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
          <VATDEALERTYPE>Regular</VATDEALERTYPE>
          <STATENAME>".$value['vendor_state']."</STATENAME>
          <VOUCHERTYPENAME>Purchase</VOUCHERTYPENAME>
          <NARRATION>".$value['narration']."</NARRATION>
          <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
          <PLACEOFSUPPLY>".$value['vendor_state']."</PLACEOFSUPPLY>
          <PARTYNAME>".$value['vendor_name']."</PARTYNAME>
          <PARTYLEDGERNAME>".$value['vendor_name']."</PARTYLEDGERNAME>
          <BUYERADDRESSTYPE/>
          <REFERENCE>".$value['invoice_code']."</REFERENCE>
          <PARTYMAILINGNAME>".$value['vendor_name']."</PARTYMAILINGNAME>
          <PARTYPINCODE>".$value['vendor_postcode']."</PARTYPINCODE>
          <CONSIGNEEMAILINGNAME>Metrics</CONSIGNEEMAILINGNAME>
          <CONSIGNEESTATENAME>West Bengal</CONSIGNEESTATENAME>
          <BASICBASEPARTYNAME>".$value['vendor_name']."</BASICBASEPARTYNAME>
          <CSTFORMISSUETYPE/>
          <CSTFORMRECVTYPE/>
          <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
          <BASICBUYERNAME>Metrics</BASICBUYERNAME>
          <PARTYADDRESSTYPE/>
          <CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME>
          <VCHGSTCLASS/>
          <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
          <DIFFACTUALQTY>No</DIFFACTUALQTY>
          <ISDELETED>No</ISDELETED>
          <ASORIGINAL>No</ASORIGINAL>
          <FORJOBCOSTING>No</FORJOBCOSTING>
          <ISOPTIONAL>No</ISOPTIONAL>
          <EFFECTIVEDATE>20220829</EFFECTIVEDATE>
          <USEFOREXCISE>No</USEFOREXCISE>
          <USEFORINTEREST>No</USEFORINTEREST>
          <USEFORGAINLOSS>No</USEFORGAINLOSS>
          <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
          <USEFORCOMPOUND>No</USEFORCOMPOUND>
          <USEFORSERVICETAX>No</USEFORSERVICETAX>
          <ISONHOLD>No</ISONHOLD>
          <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
          <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
          <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
          <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
          <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
          <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
          <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
          <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
          <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
          <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
          <ISCANCELLED>No</ISCANCELLED>
          <HASCASHFLOW>No</HASCASHFLOW>
          <ISPOSTDATED>No</ISPOSTDATED>
          <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
          <ISINVOICE>Yes</ISINVOICE>
          <MFGJOURNAL>No</MFGJOURNAL>
          <HASDISCOUNTS>No</HASDISCOUNTS>
          <ASPAYSLIP>No</ASPAYSLIP>
          <ISCOSTCENTRE>No</ISCOSTCENTRE>
          <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
          <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
          <ISVOID>No</ISVOID>
          <ORDERLINESTATUS>No</ORDERLINESTATUS>
          <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
          <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
          <CURRPARTYLEDGERNAME>".$value['vendor_name']."</CURRPARTYLEDGERNAME>
          <CURRBASICBUYERNAME>Metrics</CURRBASICBUYERNAME>
          <CURRPARTYNAME>".$value['vendor_name']."</CURRPARTYNAME>
          <CURRBUYERADDRESSTYPE/>
          <CURRPARTYADDRESSTYPE/>
          <CURRSTATENAME>".$value['vendor_state']."</CURRSTATENAME>
          <CURRBASICSHIPDELIVERYNOTE/>
          <ISCSTAGTFORMC>No</ISCSTAGTFORMC>
          <TEMPGSTVCHDESTINATIONSTATE>West Bengal</TEMPGSTVCHDESTINATIONSTATE>
          <TEMPGSTPARTYLEDLOCTYPE>Interstate</TEMPGSTPARTYLEDLOCTYPE>
          <TEMPGSTPARTYDEALERTYPE>Regular</TEMPGSTPARTYDEALERTYPE>
          <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
          <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
          <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
          <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
          <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
          <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
          <LEDGERENTRIES.LIST>
            <LEDGERNAME>".$value['vendor_name']."</LEDGERNAME>
            <GSTCLASS/>
            <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
            <LEDGERFROMITEM>No</LEDGERFROMITEM>
            <ISPARTYLEDGER>No</ISPARTYLEDGER>
            <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
            <AMOUNT>".number_format($value['total_amount'],2,'.',',')."</AMOUNT>
            <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
            <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
            <BILLALLOCATIONS.LIST>
            <NAME>".$value['invoice_code']."</NAME>
            <BILLTYPE>New Ref</BILLTYPE>
            <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
            <AMOUNT>".number_format($value['total_amount'],2,'.',',')."</AMOUNT>
            <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
            <STBILLCATEGORIES.LIST>        </STBILLCATEGORIES.LIST>
            </BILLALLOCATIONS.LIST>
            <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
            <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
            <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
            <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
            <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
            <INVENTORYALLOCATIONS.LIST>       </INVENTORYALLOCATIONS.LIST>
            <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
            <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
            <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
            <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
            <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
            <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
            <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
            <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
            <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
            <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
            <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
          </LEDGERENTRIES.LIST>
          ".$xmllines."
          ".$xmllinesTax."
          <VCHLEDTOTALTREE.LIST>      </VCHLEDTOTALTREE.LIST>
          <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
          <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
          </VOUCHER>
        </TALLYMESSAGE>
        </REQUESTDATA>
      </IMPORTDATA>
      </BODY>
      </ENVELOPE>";

   //echo $xml;die;


    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_PORT => "9000",
      CURLOPT_URL => "http://localhost:9000",
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => "",
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 30,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => "POST",
      CURLOPT_POSTFIELDS =>$xml,
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
      echo "cURL Error #:" . $err;
  } else {
      echo $response;
  }


?>