<?php
if (isset($_SERVER['HTTP_ORIGIN'])) {
  //header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
  header("Access-Control-Allow-Origin: *");
  header('Access-Control-Allow-Credentials: true');    
  header("Access-Control-Allow-Methods: GET, POST, OPTIONS"); 
}   
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
      header("Access-Control-Allow-Methods: GET, POST, OPTIONS");         
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
      header("Access-Control-Allow-Headers:{$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

  exit(0);
}

$value = $_POST;
print_r($value);die;
$name =  str_replace("&","&amp;",$value['customer_name']);

$xml="<ENVELOPE>
<HEADER>
 <TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>
<BODY>
 <IMPORTDATA>
  <REQUESTDESC>
   <REPORTNAME>Vouchers</REPORTNAME>
   <STATICVARIABLES>
    <SVCURRENTCOMPANY>".$value['unit_description']."</SVCURRENTCOMPANY>
   </STATICVARIABLES>
  </REQUESTDESC>
  <REQUESTDATA>
   <TALLYMESSAGE xmlns:UDF='TallyUDF'>
    <VOUCHER REMOTEID=''  VCHTYPE='Receipt' ACTION='Create' OBJVIEW='Accounting Voucher View'>
     <DATE>20230401</DATE>
     <VOUCHERTYPENAME>Receipt</VOUCHERTYPENAME>
     <PARTYLEDGERNAME>".$name."</PARTYLEDGERNAME>
     <VOUCHERNUMBER>".$value['payment_no']."</VOUCHERNUMBER>
     <CSTFORMISSUETYPE/>
     <CSTFORMRECVTYPE/>
     <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
     <PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
     <VCHGSTCLASS/>
     <DIFFACTUALQTY>No</DIFFACTUALQTY>
     <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
     <ISDELETED>No</ISDELETED>
     <ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED>
     <ASORIGINAL>No</ASORIGINAL>
     <AUDITED>No</AUDITED>
     <FORJOBCOSTING>No</FORJOBCOSTING>
     <ISOPTIONAL>No</ISOPTIONAL>
     <EFFECTIVEDATE>20230401</EFFECTIVEDATE>
     <USEFOREXCISE>No</USEFOREXCISE>
     <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
     <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
     <USEFORINTEREST>No</USEFORINTEREST>
     <USEFORGAINLOSS>No</USEFORGAINLOSS>
     <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
     <USEFORCOMPOUND>No</USEFORCOMPOUND>
     <USEFORSERVICETAX>No</USEFORSERVICETAX>
     <ISONHOLD>No</ISONHOLD>
     <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
     <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
     <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
     <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
     <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
     <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
     <EXCISEOPENING>No</EXCISEOPENING>
     <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
     <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
     <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
     <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
     <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
     <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
     <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
     <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
     <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
     <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
     <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
     <ISISDVOUCHER>No</ISISDVOUCHER>
     <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
     <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
     <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
     <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
     <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
     <ISGSTREFUND>No</ISGSTREFUND>
     <OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY>
     <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
     <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
     <IRNJSONEXPORTED>No</IRNJSONEXPORTED>
     <IRNCANCELLED>No</IRNCANCELLED>
     <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
     <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
     <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
     <ISCANCELLED>No</ISCANCELLED>
     <HASCASHFLOW>Yes</HASCASHFLOW>
     <ISPOSTDATED>No</ISPOSTDATED>
     <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
     <ISINVOICE>No</ISINVOICE>
     <MFGJOURNAL>No</MFGJOURNAL>
     <HASDISCOUNTS>No</HASDISCOUNTS>
     <ASPAYSLIP>No</ASPAYSLIP>
     <ISCOSTCENTRE>No</ISCOSTCENTRE>
     <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
     <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
     <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
     <ISVOID>No</ISVOID>
     <ORDERLINESTATUS>No</ORDERLINESTATUS>
     <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
     <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
     <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
     <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
     <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
     <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
     <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
     <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
     <CHANGEVCHMODE>No</CHANGEVCHMODE>
     <RESETIRNQRCODE>No</RESETIRNQRCODE>
     <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
     <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
     <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
     <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
     <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
     <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
     <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
     <EWAYBILLERRORLIST.LIST>      </EWAYBILLERRORLIST.LIST>
     <IRNERRORLIST.LIST>      </IRNERRORLIST.LIST>
     <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
     <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
     <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
     <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
     <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
     <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
     <ALLLEDGERENTRIES.LIST>
      <LEDGERNAME>".$name."</LEDGERNAME>
      <GSTCLASS/>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>".number_format($value['payment_amount'],2,'.',',')."</AMOUNT>
      <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>
       <NAME>".$value['invoice_code']."</NAME>
       <BILLTYPE>Agst Ref</BILLTYPE>
       <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
       <AMOUNT>".number_format($value['payment_amount'],2,'.',',')."</AMOUNT>
       <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
       <STBILLCATEGORIES.LIST>        </STBILLCATEGORIES.LIST>
      </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
      <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
     </ALLLEDGERENTRIES.LIST>
     <ALLLEDGERENTRIES.LIST>
      <LEDGERNAME>".$value['payment_method']."</LEDGERNAME>
      <GSTCLASS/>
      <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>-".number_format($value['payment_amount'],2,'.',',')."</AMOUNT>
      <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
      <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
     </ALLLEDGERENTRIES.LIST>
     <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
     <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
     <GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>
     <GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>
     <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
    </VOUCHER>
   </TALLYMESSAGE>
   <TALLYMESSAGE xmlns:UDF='TallyUDF'>
    <COMPANY>
     <REMOTECMPINFO.LIST MERGE='Yes'>
      <REMOTECMPNAME>".$value['unit_description']."</REMOTECMPNAME>
     </REMOTECMPINFO.LIST>
    </COMPANY>
   </TALLYMESSAGE>
   <TALLYMESSAGE xmlns:UDF='TallyUDF'>
    <COMPANY>
     <REMOTECMPINFO.LIST MERGE='Yes'>
      <REMOTECMPNAME>".$value['unit_description']."</REMOTECMPNAME>
     </REMOTECMPINFO.LIST>
    </COMPANY>
   </TALLYMESSAGE>
  </REQUESTDATA>
 </IMPORTDATA>
</BODY>
</ENVELOPE>";

//echo $xml;die;

    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_PORT => "9000",
    CURLOPT_URL => "http://localhost:9000",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS =>$xml,
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    //echo $response;die;

    if ($err) {
        //echo "cURL Error #:" . $err;
        print_r(json_encode(array('status' => '0','msg' =>$err)));
      } else {
        $xmlResponse = simplexml_load_string($response);
        $json = json_encode($xmlResponse);
        $decode = json_decode($json,true);
      
        if(array_key_exists("LINEERROR",$decode))
        {
          //array_push($errorDataArray,'Error : '.$decode['LINEERROR']);
          print_r(json_encode(array('status' => '0','msg'=>$decode['LINEERROR'])));
      
        }else {
      
           //echo  $response1;
      
           if($decode['CREATED'] == '1'|| $decode['ALTERED'] == '1' )
           {
      
             print_r(json_encode(array('status' => '1','guid'=>'1'.'+'.$value['unit_id'].'+'.$value['organization_id'])));
           }elseif($decode->ERRORS == '1') {
      
             print_r(json_encode(array('status' => '0','msg'=>$decode['LINEERROR'])));
           }else {
             
             print_r(json_encode(array('status' => '0','msg'=>'Something went wrong, please try sometimes later')));
           }
      
        }
         
          
      }
    
?>


