<?php
if (isset($_SERVER['HTTP_ORIGIN'])) {
  //header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
  header("Access-Control-Allow-Origin: *");
  header('Access-Control-Allow-Credentials: true');    
  header("Access-Control-Allow-Methods: GET, POST, OPTIONS"); 
}   
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
      header("Access-Control-Allow-Methods: GET, POST, OPTIONS");         
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
      header("Access-Control-Allow-Headers:{$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

  exit(0);
}


$value = $_POST;
print_r($value);die;
$date=date_create($value['invoice_date']);
$invoice_date= date_format($date,"Ymd");
$name =  str_replace("&","&amp;",$value['customer_name']);
$address1=  str_replace("&","&amp;",$value['customer_site_addr1']);
$customer_gst=  str_replace("GSTIN:","",$_POST['customer_gst']);

$xmllinesTax = '';
$total = 0;

foreach($value['invoice_tax'] as $linesTax)
{
    $gst = $linesTax['tax_code'];
    $total = $total + $linesTax["tax_value"];
    $xmllinesTax.= "<LEDGERENTRIES.LIST>
    <ROUNDTYPE/>
    <LEDGERNAME>".$gst."</LEDGERNAME>
    <VOUCHERFBTCATEGORY/>
    <GSTCLASS/>
    <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
    <LEDGERFROMITEM>No</LEDGERFROMITEM>
    <ISPARTYLEDGER>No</ISPARTYLEDGER>
    <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
    <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
    <AMOUNT>-".$linesTax["tax_value"]."</AMOUNT>
    <VATEXPAMOUNT>-".$linesTax["tax_value"]."</VATEXPAMOUNT>
    <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
    <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
    <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
    <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
    <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
    <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
    <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
    <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
    <INVENTORYALLOCATIONS.LIST>       </INVENTORYALLOCATIONS.LIST>
    <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
    <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
    <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
    <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
    <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
    <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
    <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
    <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
    <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
    <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
    <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
    <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
    <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
    <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
   </LEDGERENTRIES.LIST>";

}

$xmllines = '';

foreach($value['invoice_lines'] as $lines)
{
    //$quentity = floatval($lines['quantity']);
    $line_description=  str_replace("&","&amp;",$lines['description']);
    $total = $total + $lines['line_amount'];

    $xmllines.="<ALLINVENTORYENTRIES.LIST>
      <BASICUSERDESCRIPTION.LIST TYPE='String'>
        <BASICUSERDESCRIPTION>".$line_description."</BASICUSERDESCRIPTION>
      </BASICUSERDESCRIPTION.LIST>
      <STOCKITEMNAME>Item</STOCKITEMNAME>
      <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
      <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
      <ISAUTONEGATE>No</ISAUTONEGATE>
      <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
      <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
      <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
      <ISPRIMARYITEM>No</ISPRIMARYITEM>
      <ISSCRAP>No</ISSCRAP>
      <RATE>".number_format($lines['unit_price'],2,'.',',')."</RATE>
      <DISCOUNT>".$lines['discount_percentage']."</DISCOUNT>
      <AMOUNT>-".number_format($lines['line_amount'],2,'.',',')."</AMOUNT>
      <ACTUALQTY> ".$lines['quantity']."</ACTUALQTY>
      <BILLEDQTY>".$lines['quantity']."</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <INDENTNO/>
        <ORDERNO/>
        <TRACKINGNUMBER/>
        <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
        <AMOUNT>-".number_format($lines['line_amount'],2,'.',',')."</AMOUNT>
        <ACTUALQTY>".$lines['quantity']."</ACTUALQTY>
        <BILLEDQTY>".$lines['quantity']."</BILLEDQTY>
        <ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
        <VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
        <OLDAUDITENTRYIDS.LIST TYPE='Number'>
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
        </OLDAUDITENTRYIDS.LIST>
        <LEDGERNAME>".$lines['account_code_description']."</LEDGERNAME>
        <GSTCLASS/>
        <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
        <LEDGERFROMITEM>No</LEDGERFROMITEM>
        <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
        <ISPARTYLEDGER>No</ISPARTYLEDGER>
        <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
        <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
        <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
        <AMOUNT>-".number_format($lines['line_amount'],2,'.',',')."</AMOUNT>
        <SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
        <BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
        <BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
        <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
        <OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
        <INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
        <DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
        <EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
        <RATEDETAILS.LIST>        </RATEDETAILS.LIST>
        <SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
        <STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
        <EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
        <TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
        <TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
        <TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
        <VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
        <COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
        <REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
        <INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
        <VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
        <ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
      </ACCOUNTINGALLOCATIONS.LIST>
      <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
      <SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
      <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
      <EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
      <EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
      </ALLINVENTORYENTRIES.LIST>";
}

$xml = "";
$xml.= "<ENVELOPE>
<HEADER>
 <TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>
<BODY>
 <IMPORTDATA>
  <REQUESTDESC>
   <REPORTNAME>Vouchers</REPORTNAME>
   <STATICVARIABLES>
    <SVCURRENTCOMPANY>".$value['unit_description']."</SVCURRENTCOMPANY>
   </STATICVARIABLES>
  </REQUESTDESC>
  <REQUESTDATA>
   <TALLYMESSAGE xmlns:UDF='TallyUDF'>
    <VOUCHER VCHTYPE='Credit Note' ACTION='Create' OBJVIEW='Invoice Voucher View'>
     <ADDRESS.LIST TYPE='String'>
      <ADDRESS>".$address1."</ADDRESS>
     </ADDRESS.LIST>
     <BASICBUYERADDRESS.LIST TYPE='String'>
      <BASICBUYERADDRESS>".$address1."</BASICBUYERADDRESS>
     </BASICBUYERADDRESS.LIST>
     <DATE>20230401</DATE>
     <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
     <VATDEALERTYPE>Regular</VATDEALERTYPE>
     <STATENAME>".$value['customer_site_city']."</STATENAME>
     <VOUCHERTYPENAME>Credit Note</VOUCHERTYPENAME>
     <COUNTRYOFRESIDENCE>".$value['customer_country']."</COUNTRYOFRESIDENCE>
     <PARTYGSTIN>".$customer_gst."</PARTYGSTIN>
     <PLACEOFSUPPLY>".$value['customer_site_city']."</PLACEOFSUPPLY>
     <PARTYNAME>".$name."</PARTYNAME>
     <PARTYLEDGERNAME>".$name."</PARTYLEDGERNAME>
     <PARTYMAILINGNAME>".$name."</PARTYMAILINGNAME>
     <PARTYPINCODE>".$value['customer_site_postcode']."</PARTYPINCODE>
     <CONSIGNEEMAILINGNAME>".$name."</CONSIGNEEMAILINGNAME>
     <CONSIGNEEPINCODE>".$value['customer_site_postcode']."</CONSIGNEEPINCODE>
     <CONSIGNEESTATENAME>".$value['customer_site_city']."</CONSIGNEESTATENAME>
     <VOUCHERNUMBER>CR-295</VOUCHERNUMBER>
     <BASICBASEPARTYNAME>".$name."</BASICBASEPARTYNAME>
     <CSTFORMISSUETYPE/>
     <CSTFORMRECVTYPE/>
     <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
     <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
     <BASICBUYERNAME>".$name."</BASICBUYERNAME>
     <CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME>
     <VCHGSTCLASS/>
     <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
     <DIFFACTUALQTY>No</DIFFACTUALQTY>
     <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
     <ISDELETED>No</ISDELETED>
     <ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED>
     <ASORIGINAL>No</ASORIGINAL>
     <AUDITED>No</AUDITED>
     <FORJOBCOSTING>No</FORJOBCOSTING>
     <ISOPTIONAL>No</ISOPTIONAL>
     <EFFECTIVEDATE>20230401</EFFECTIVEDATE>
     <USEFOREXCISE>No</USEFOREXCISE>
     <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
     <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
     <USEFORINTEREST>No</USEFORINTEREST>
     <USEFORGAINLOSS>No</USEFORGAINLOSS>
     <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
     <USEFORCOMPOUND>No</USEFORCOMPOUND>
     <USEFORSERVICETAX>No</USEFORSERVICETAX>
     <ISONHOLD>No</ISONHOLD>
     <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
     <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
     <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
     <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
     <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
     <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
     <EXCISEOPENING>No</EXCISEOPENING>
     <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
     <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
     <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
     <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
     <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
     <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
     <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
     <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
     <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
     <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
     <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
     <ISISDVOUCHER>No</ISISDVOUCHER>
     <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
     <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
     <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
     <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
     <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
     <ISGSTREFUND>No</ISGSTREFUND>
     <OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY>
     <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
     <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
     <IRNJSONEXPORTED>No</IRNJSONEXPORTED>
     <IRNCANCELLED>No</IRNCANCELLED>
     <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
     <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
     <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
     <ISCANCELLED>No</ISCANCELLED>
     <HASCASHFLOW>No</HASCASHFLOW>
     <ISPOSTDATED>No</ISPOSTDATED>
     <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
     <ISINVOICE>Yes</ISINVOICE>
     <MFGJOURNAL>No</MFGJOURNAL>
     <HASDISCOUNTS>Yes</HASDISCOUNTS>
     <ASPAYSLIP>No</ASPAYSLIP>
     <ISCOSTCENTRE>No</ISCOSTCENTRE>
     <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
     <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
     <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
     <ISVOID>No</ISVOID>
     <ORDERLINESTATUS>No</ORDERLINESTATUS>
     <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
     <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
     <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
     <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
     <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
     <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
     <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
     <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
     <CHANGEVCHMODE>No</CHANGEVCHMODE>
     <RESETIRNQRCODE>No</RESETIRNQRCODE>
     <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
     <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
     <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
     <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
     <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
     <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
     ".$xmllines."
     <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
     <EWAYBILLERRORLIST.LIST>      </EWAYBILLERRORLIST.LIST>
     <IRNERRORLIST.LIST>      </IRNERRORLIST.LIST>
     <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
     <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
     <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
     <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
     <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
     <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
     <LEDGERENTRIES.LIST>
      <LEDGERNAME>".$name."</LEDGERNAME>
      <GSTCLASS/>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>".number_format($total,2,'.',',')."</AMOUNT>
      <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>
       <NAME>".$value['invoice_code']."</NAME>
       <BILLTYPE>New Ref</BILLTYPE>
       <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
       <AMOUNT>".number_format($total,2,'.',',')."</AMOUNT>
       <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
       <STBILLCATEGORIES.LIST>        </STBILLCATEGORIES.LIST>
      </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
      <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
     </LEDGERENTRIES.LIST>
     ".$xmllinesTax."
     <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
     <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
     <GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>
     <GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>
     <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
    </VOUCHER>
   </TALLYMESSAGE>
   <TALLYMESSAGE xmlns:UDF='TallyUDF'>
    <COMPANY>
     <REMOTECMPINFO.LIST MERGE='Yes'>
      <REMOTECMPNAME>".$value['unit_description']."</REMOTECMPNAME>
     </REMOTECMPINFO.LIST>
    </COMPANY>
   </TALLYMESSAGE>
   <TALLYMESSAGE xmlns:UDF='TallyUDF'>
    <COMPANY>
     <REMOTECMPINFO.LIST MERGE='Yes'>
      <REMOTECMPNAME>".$value['unit_description']."</REMOTECMPNAME>
     </REMOTECMPINFO.LIST>
    </COMPANY>
   </TALLYMESSAGE>
  </REQUESTDATA>
 </IMPORTDATA>
</BODY>
</ENVELOPE>";

//echo $xml;die;

    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_PORT => "9000",
    CURLOPT_URL => "http://localhost:9000",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS =>$xml,
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
      //echo "cURL Error #:" . $err;
      print_r(json_encode(array('status' => '0','msg' =>$err)));
    } else {
      $xmlResponse = simplexml_load_string($response);
      $json = json_encode($xmlResponse);
      $decode = json_decode($json,true);
    
      if(array_key_exists("LINEERROR",$decode))
      {
        //array_push($errorDataArray,'Error : '.$decode['LINEERROR']);
        print_r(json_encode(array('status' => '0','msg'=>$decode['LINEERROR'])));
    
      }else {
    
         //echo  $response1;
    
         if($decode['CREATED'] == '1'|| $decode['ALTERED'] == '1' )
         {
    
           print_r(json_encode(array('status' => '1','guid'=>'1'.'+'.$value['unit_id'].'+'.$value['organization_id'])));
         }elseif($decode->ERRORS == '1') {
    
           print_r(json_encode(array('status' => '0','msg'=>$decode['LINEERROR'])));
         }else {
           
           print_r(json_encode(array('status' => '0','msg'=>'Something went wrong, please try sometimes later')));
         }
    
      }
       
        
    }
    
?>


